<?php

namespace ContainerCT6rC4L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStockCalculationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\StockCalculationController' shared autowired service.
     *
     * @return \App\Controller\StockCalculationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/StockCalculationController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/CalculateStock.php';

        $a = ($container->privates['App\\Repository\\WarehouseRepository'] ?? $container->load('getWarehouseRepositoryService'));
        $b = ($container->privates['App\\Repository\\StockCalculationRepository'] ?? $container->load('getStockCalculationRepositoryService'));
        $c = ($container->privates['validator'] ?? $container->load('getValidatorService'));

        $container->services['App\\Controller\\StockCalculationController'] = $instance = new \App\Controller\StockCalculationController($a, $b, $c, new \App\Service\CalculateStock($a, $b, $c));

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
        ], [
            'http_kernel' => '?',
            'parameter_bag' => '?',
            'request_stack' => '?',
            'router' => '?',
        ]))->withContext('App\\Controller\\StockCalculationController', $container));

        return $instance;
    }
}
