<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_stock_calculation' => [['shop', 'product'], ['_format' => 'application/json', '_controller' => 'App\\Controller\\StockCalculationController::check'], [], [['text', '/'], ['variable', '/', '[^/]++', 'product', true], ['variable', '/', '[^/]++', 'shop', true], ['text', '/stock']], [], [], []],
];
